export const TRASH_RETENTION_DAYS: number = 30;
export const QUARANTINE_RETENTION_DAYS: number = 30;
export const VERSION_RETENTION_DAYS: number = 30;

const DAY_MS = 24 * 60 * 60 * 1000;

export const TRASH_RETENTION_MS = TRASH_RETENTION_DAYS * DAY_MS;
export const QUARANTINE_RETENTION_MS = QUARANTINE_RETENTION_DAYS * DAY_MS;
export const VERSION_RETENTION_MS = VERSION_RETENTION_DAYS * DAY_MS;
